# Generated by Django 3.0.5 on 2020-04-26 20:21

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to='produtos', verbose_name='Imagem'),
        ),
    ]
